/control/verbose 2
/run/verbose 2

#/testhadr/ListPhysics
#/testhadr/Physics QBBC

#/physics_lists/select QGSC_BERT_EMZ
#/physics_lists/factory/addOptical

#/process/optical/verbose 2

#/process/optical/cerenkov/setMaxPhotons 3
#/process/optical/cerenkov/setMaxBetaChange 10

#/process/optical/scintillation/setExcitationRatio .5
#/process/optical/scintillation/setByParticleType false
#/process/optical/scintillation/setTrackInfo      false
#/process/optical/scintillation/setFiniteRiseTime true
#/process/optical/scintillation/setStackPhotons   true

# Turn off Cherenkov process
/process/optical/processActivation Cerenkov      false
/process/optical/processActivation OpAbsorption  false
/process/optical/processActivation OpBoundary    false
/process/optical/processActivation Scintillation true
/process/optical/processActivation OpRayleigh    false
/process/optical/processActivation OpMieHG       false
/process/optical/processActivation OpWLS         false

/NPS_Energy_Resolution/det/setCrystalSize 20 20 200 mm

/run/initialize

#/vis/ASCIITree/verbose 10
#/vis/drawTree

/gps/source/intensity 1
/gps/particle e-
/gps/pos/type Point
/gps/ene/mono 1 GeV
/gps/pos/centre 0.  0. -2000. mm
/gps/direction 0. 0. 1.
/gps/source/multiplevertex true
/gps/source/list


/process/list

#/run/printProgress 1
/tracking/verbose 2
/run/beamOn 1

# Turn off visualization
##### /vis/disable
#/tracking/verbose 0
#/run/beamOn 25
