# Set verbose level of the control (macro) file
/control/verbose 2

# Set verbose level of the RunManager 
/run/verbose 1

# Specify the physics (TODO: try other physics)
# /testhadr/Physics QBBC
# /testhadr/Physics optical

# Crystal size along X, Y and Z axis
/detector/setCrystalSize 20 20 200 mm

# Crystal material - currently supported values are BaGdSiO, BaSi2O5, PbWO4
/detector/setCrystalMaterial PbWO4

# Number of crystals in the assembly along X and Y axis
/detector/setCrystalNumberX 1
/detector/setCrystalNumberY 1

# Detector type (PMT or MPPC)
/detector/setDetectorType PMT

# PMT window diameter (18 mm for R4125, 56 mm for H3177)
/detector/setPmtDiameter 18 mm
/detector/setGreaseThickness 0.2 mm

/histoManager/setOutputFileNamePattern %s-%dx%d-%.2fmm-%.2fmm-%.2fmm_%.1fGeV_%devents.root
/histoManager/writeWorldEscape false

#/process/optical/verbose 2

# Control optical processes
#/process/optical/processActivation Cerenkov      true
#/process/optical/processActivation OpAbsorption  true
#/process/optical/processActivation OpBoundary    true
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation OpRayleigh    false
#/process/optical/processActivation OpMieHG       false
#/process/optical/processActivation OpWLS         false

#/process/optical/scintillation/setExcitationRatio .5
#/process/optical/scintillation/setByParticleType false
#/process/optical/scintillation/setTrackInfo      false
#/process/optical/scintillation/setFiniteRiseTime false
#/process/optical/scintillation/setStackPhotons   false

#/process/optical/cerenkov/setMaxPhotons 3
#/process/optical/cerenkov/setMaxBetaChange 10

/run/initialize

/geometry/test/run

/process/list

# Incident particle type, energy and direction
/gps/source/intensity 1
/gps/particle gamma
/gps/pos/type Point
/gps/ene/mono 0.5 MeV
/gps/pos/centre 0.  0. -40. mm
/gps/direction 0. 0. 1.
# /gps/source/multiplevertex true
/gps/source/list

# /vis/list
# OpenGLStoredQt (OGLSQt, OGL, OGLS) - cannot have trajectories and mesh, legend disappears when move
/vis/open OGL
# OpenGLImmediateQt (OGLIQt, OGLI) - cannot draw mesh after trajectories
#/vis/open OGLIQt
# OpenGLImmediateXm (OGLIXm, OGLIQt_FALLBACK) - separate window, freezes
#/vis/open OGLIXm
# OpenGLStoredXm (OGLSXm, OGLSQt_FALLBACK) - separate window, freezes
#/vis/open OGLSXm
# OpenGLImmediateX (OGLIX, OGLIQt_FALLBACK, OGLIXm_FALLBACK) - separate window, everything works!
#/vis/open OGLIX
# OpenGLStoredX (OGLSX, OGLSQt_FALLBACK, OGLSXm_FALLBACK) - no trajectories with scorer
# /vis/open OGLSX


/vis/ogl/set/displayListLimit 500000
#/vis/open VRML2FILE
#/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/trajectories
#/vis/scene/add/axes 0 0 0 10 cm
#/vis/scene/endOfEventAction accumulate 10

/run/beamOn 10

# https://geant4.web.cern.ch/sites/geant4.web.cern.ch/files/geant4/collaboration/workshops/users2002/talks/README.built_in_commands.txt


# Camera pivot point
# /vis/viewer/set/targetPoint 0 0 145 mm
# Direction from target to camera
# /vis/viewer/set/viewpointVector -1 1 -1
# Zoom level
#/vis/viewer/zoomTo 50

# Set light to camera
#/vis/viewer/set/lightsMove with-camera

# Center camera on the crystal and PMT assembly
/myvis/centerViewer

# Draw energy deposition projections 
# /score/drawProjection crystalsMesh eneDepCrystal myColorMap
# /score/drawProjection pmtsMesh eneDepPMT myColorMap

# Output statistics
# /myvis/drawStats

# Save scoring mesh data
#/score/dumpAllQuantitiesToFile crystalsMesh crystalsMesh.txt
#/score/dumpAllQuantitiesToFile pmtsMesh pmtsMesh.txt

# Close visualization
#/vis/disable

# Number of events for the energy resolution run
#/histoManager/writeWorldEscape false
#/tracking/verbose 0
#/run/verbose 0
#/run/beamOn 1000